name: 'lh_lease_notice'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  lh_lease_notice:
    staging:
      +materialized: view
      +schema: public
    intermediate:
      +materialized: view
      +schema: public
    marts:
      +materialized: table
      +schema: public
      bi:
        +materialized: table
      app:
        +materialized: table
